@startuml

actor EMP as "Employee"
rectangle "App" {
    usecase UC1 as "Country Report"
    usecase UC2 as "City Report"
    usecase UC3 as "Capital City Report"
    usecase UC4 as "Population Report"
    usecase UC5 as "Population Query"
    usecase UC6 as "Language Report"
    EMP --> UC1
    EMP --> UC2
    EMP --> UC3
    EMP --> UC4
    EMP --> UC5
    EMP --> UC6
}
@enduml